name: Daily News Update

on:
  schedule:
    # Schedule to run at 9 AM and 6 PM UTC daily
    - cron: "0 9,18 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the workflow to commit and push changes

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 transformers pandas matplotlib scikit-learn prophet wordcloud torch plotly


    # Step 4: Run the Python script
    - name: Run daily news script
      run: python daily_news.py

    - name: Check files before commit
      run: ls -la

    # Step 5: Commit and push changes
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "poonia197020@gmail.com"
        git config --global user.name "anmolpoonia"
        git add . -- ':!report.pdf' ':!README.md'
        git commit -m "Staging changes before pulling" || echo "No changes to commit"
        git pull --rebase origin main
        git add . -- ':!report.pdf' ':!README.md'
        git commit -m "Automated daily update" || echo "No changes to commit"
        git push --force
